/*
 * game.h
 * game controller that manages turns and communication with prolog and racket
 */

#ifndef GAME_H
#define GAME_H

#include "board.h"
#include <string>
#include <utility>

/* game class manages the board, turn order, and language integration */
class Game
{
private:
    /* board used for storing game state */
    Board board;

    /* tracks which player is active */
    int currentPlayer;

    /* true when the game ends */
    bool gameOver;

    /* winner value (1 or 2), 0 for running, -1 for draw */
    int winner;

    /* file used to store board state */
    const std::string STATE_FILE = "data/current_state.txt";

    /* file used to store move queries */
    const std::string QUERY_FILE = "data/move_query.txt";

    /* file used to store validation or ai responses */
    const std::string RESPONSE_FILE = "data/move_response.txt";

public:
    /* create a new game with a board of a given size */
    Game(int size);

    /* display the board and current player */
    void display() const;

    /* attempt to apply a move */
    bool makeMove(int row, int col);

    /* validate a move using prolog */
    bool validateMoveWithProlog(int row, int col);

    /* get ai move generated by racket */
    std::pair<int, int> getAIMoveFromScheme();

    /* check whether the game has ended */
    bool isGameOver() const;

    /* return winner value */
    int getWinner() const;

    /* switch active player */
    void switchPlayer();

    /* return current player number */
    int getCurrentPlayer() const;

private:
    /* write the board state to disk */
    void saveBoardState();

    /* evaluate board for a win or draw */
    void checkWinner();
};

#endif // GAME_H